// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB293qmA6Cp0qorBZ7CHQPSms_PSuaiOfg',
    appId: '1:419540803823:web:ae07825469480695b03b1a',
    messagingSenderId: '419540803823',
    projectId: 'klizards-6909a',
    authDomain: 'klizards-6909a.firebaseapp.com',
    storageBucket: 'klizards-6909a.appspot.com',
    measurementId: 'G-44TCN4EVDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9wtxyNRdjt2YYZla2ENBM0V3strphTzo',
    appId: '1:419540803823:android:424bebe69acd5fbeb03b1a',
    messagingSenderId: '419540803823',
    projectId: 'klizards-6909a',
    storageBucket: 'klizards-6909a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCha17Xk1Ndzo2USIPIjbtbUfj-wQXXSUw',
    appId: '1:419540803823:ios:6221bb05b5ba1a08b03b1a',
    messagingSenderId: '419540803823',
    projectId: 'klizards-6909a',
    storageBucket: 'klizards-6909a.appspot.com',
    iosBundleId: 'com.app.klizard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCha17Xk1Ndzo2USIPIjbtbUfj-wQXXSUw',
    appId: '1:419540803823:ios:114591cbaedaa9c9b03b1a',
    messagingSenderId: '419540803823',
    projectId: 'klizards-6909a',
    storageBucket: 'klizards-6909a.appspot.com',
    iosBundleId: 'com.example.klizards',
  );
}
