// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOMv-DAXsKDhK6Po_n76B4CiOldK9Lum4',
    appId: '1:431848399390:web:dc7a4f3a40dfb924c7040f',
    messagingSenderId: '431848399390',
    projectId: 'globle-hour-marine',
    authDomain: 'globle-hour-marine.firebaseapp.com',
    storageBucket: 'globle-hour-marine.firebasestorage.app',
    measurementId: 'G-05C9HG2EYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqwDsHkAlbXbZDxj4dAMcQoItmS479Mpk',
    appId: '1:431848399390:android:e5dfca9e52487652c7040f',
    messagingSenderId: '431848399390',
    projectId: 'globle-hour-marine',
    storageBucket: 'globle-hour-marine.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPN0rxK50diPjWh9Lcgh_I8l5O4eBR_jw',
    appId: '1:431848399390:ios:18438dc07ae20b31c7040f',
    messagingSenderId: '431848399390',
    projectId: 'globle-hour-marine',
    storageBucket: 'globle-hour-marine.firebasestorage.app',
    iosBundleId: 'com.example.ghm',
  );
}
